[package]
name = "automation_tasks_rs"
version = "1.0.0" 
authors = ["bestia.dev"]
homepage = "https://bestia.dev"
edition = "2021"
description = "cargo auto - automation tasks written in Rust language"
publish = false

[dependencies]
cargo_auto_lib = "1.3.14"
# cargo_auto_lib = {path = "/home/rustdevuser/rustprojects/cargo_auto_lib"}
